### ISSUE TITLE
Issue with process.env.HOME on Windows

### ISSUE THREAD

**Issue by volleio** [codeblog/codeblog#1]
packageUitils.ts's outputPath is returning `path.join(process.env.HOME, ``.codeblog-${mode}``, packageName)`, but process.env.HOME is not supported in Windows. [This stackoverflow answer](https://stackoverflow.com/a/32556337/8642105) recommends using os.homedir() instead.

I'd make a PR for this, but I'm not sure how to run the server locally so I can't test it.

here's the full stack trace I get:
```
$ codeblog dev
[Codeblog]          Starting dev server...
[Codeblog]          Started dev server!
[Codeblog]          Starting dev server...


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at outputPath (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334965:71)
    at CodeblogComponent.get buildPath [as buildPath] (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334391:41)
    at CodeblogComponent.start (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334272:53)
    at Function.load (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334441:21)
    at C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334449:19
    at Array.map (<anonymous>)
    at Function.loadAll (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334447:32)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async RawDevServerComponent.start (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:333926:26) Promise {
  <rejected> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:107:11)
      at Object.join (path.js:372:7)
      at outputPath (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334965:71)
      at CodeblogComponent.get buildPath [as buildPath] (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334391:41)
      at CodeblogComponent.start (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334272:53)
      at Function.load (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334441:21)
      at C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334449:19
      at Array.map (<anonymous>)
      at Function.loadAll (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:334447:32)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async RawDevServerComponent.start (C:\Users\Lucas\AppData\Roaming\npm\node_modules\codeblog\bin\codeblog:333926:26)
}
```

**Comment by Jarred-Sumner** [comment]
Oh wow, I haven't tested in windows yet. Thanks for the bug report. I will fix this.
